### ISSUE TITLE
[Unhandled promise rejection: TypeError: Network request failed]

### ISSUE THREAD

**Issue by freekatet** [cyrildiagne/ar-cutpaste#1]
everything seems to be working fine, but i keep running on a network request failed error on the Expo side.
i can see that error on both side, macbook and android phone.
:(

**Comment by freekatet** [comment]
got a bit further 

 Expo  Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
Finished building JavaScript bundle in 1422ms.
Running application on Pixel 3.
Cut
undefined
> taking image...
update
> resizing...
> sending to /cut...
> converting...
Done in 5.710s
Paste
> taking image...
update
> resizing...
> sending to /paste...
Done in 5.573s

error pasting:, [SyntaxError: JSON Parse error: Unrecognized token '<']
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
* App.tsx:102:2 in paste
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:147:19 in PromiseImpl.resolve.then$argument_1
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue

**Comment by benjaminzanatta** [comment]
Same here:

Running application on iPhone31.
Cut
undefined
> taking image...
update
> resizing...
> sending to /cut...

[Unhandled promise rejection: TypeError: Network request failed]
- node_modules/whatwg-fetch/dist/fetch.umd.js:477:29 in xhr.ontimeout
- node_modules/event-target-shim/dist/event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:572:29 in setReadyState
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by AntonBaumannDE** [comment]
second on @benjaminzanatta :/ looked into a couple of things, but didn't get any results. thanks a lot for this amazing project though! really appreciate your work

**Comment by cyrildiagne** [comment]
Hi,
I just realise that I've hardcoded my laptop IP address in https://github.com/cyrildiagne/ar-cutpaste/blob/master/app/components/Server.tsx

Could that be the issue?

**Comment by benjaminzanatta** [comment]
I changed the IP address by mine and I have the same error but right at the beginning:

Running application on iPhone31.

[Unhandled promise rejection: TypeError: Network request failed]
- node_modules/whatwg-fetch/dist/fetch.umd.js:473:29 in xhr.onerror
- node_modules/event-target-shim/dist/event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:574:29 in setReadyState
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by cyrildiagne** [comment]
@benjaminzanatta I've added a log on the `server.ping()` method that is called at startup in c47c5ef0ac4f4ab416c7e8fd34ef4bb15090dfa6

Could you try pull and trying again? (making sure both your laptop and mobile are on the same wifi & able to communicate)

**Comment by LeomaxDesign** [comment]
@cyrildiagne I found that error happeing at this func (namely in the fetch request)

`async function cut(imageURI: string) {
  const formData = new FormData();
  formData.append("data", {
    uri: imageURI,
    name: "photo",
    type: "image/jpg",
  });

  const resp = await fetch(URL + "/cut", {
    method: "POST",
    body: formData,
  }).then(async (res) => {
    console.log("> converting...");
    const buffer = await res.arrayBuffer();
    const base64Flag = "data:image/png;base64,";
    const imageStr = arrayBufferToBase64(buffer);
    return base64Flag + imageStr;
  });

  return resp;
}`
Also I checked /ping requst and its working good. Mby it works differently on different versions?

**Comment by benjaminzanatta** [comment]
I have this now:

Running application on iPhone31.

Network request failed
- node_modules/whatwg-fetch/dist/fetch.umd.js:473:29 in xhr.onerror
- node_modules/event-target-shim/dist/event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:574:29 in setReadyState
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by yahongie2014** [comment]
i face that error
![image](https://user-images.githubusercontent.com/5874360/81020742-d1282200-8e69-11ea-84ba-69816a481c89.png)

**Comment by minhratcool** [comment]
`Cut
undefined
> taking image...
update
> resizing...
> sending to /cut...

[Unhandled promise rejection: TypeError: Network request failed]
- node_modules/whatwg-fetch/dist/fetch.umd.js:473:29 in xhr.onerror
- node_modules/event-target-shim/dist/event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:574:29 in setReadyState
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
`
I have this too and cant figure out the problems yet. 
As for now:
* Phone ping to server: OK
* server ping to basnett: OK
* not sure if photoshop connection is working

**Comment by jatin-bodara** [comment]
I have faced same above error.

**Comment by cyrildiagne** [comment]
Does the BASNet service work correctly when called directly with cURL or Postman?

**Comment by LeomaxDesign** [comment]
Dont know how, but after PC reboot all working good

**Comment by minhratcool** [comment]
Well I have passed this error! 
First to describe the issue, I initially set `const URL = "http://0.0.0.0:8080";` in `/app/components/Server.tsx` as I though this app would run on my PC and call to server just by using localhost but in fact the api calls will be executed from my phone so it can't ping to the server through local address. 
Which makes me changed the URL to `const URL = "http://192.168.1.11:8080";` (will be different on yours), and the magic happens now ^^. 
So far I have been able to cut and paste things to a Photoshop window but the results are still blank layers, I think there are some more configs needed to be made within the Photoshop application to allow some color profiles to display? (Im not familiar with Photoshop at all, totally an outsider)
Anyway, I will keep coming back with better results hopefully.

**Comment by freekatet** [comment]
problem solved on my side.
my only mistake was that i changed the port on the main server instead of the one on BASNet server (obviously didn't make sense...)

so to make it clear, i only changed the port number on the main.py from the BASNET-http (to avoid having both servers running locally on port 8080, made BASNET server on 3000)
@cyrildiagne it should maybe be mentioned on the ARcut README to avoid any confusion.

I ran in an other problem where the server didn't seem to send anything to photoshop ( i could see mask, current, received happening in the server folder tho)

Everything worked perfectly after rebooting.
All of this between an android and MacBook.

hope it will help.

**Comment by cyrildiagne** [comment]
Thanks @freekatet
Added a notice.

**Comment by NielEche** [comment]
Hello please i'm still having the same issue with @benjaminzanatta , i cant figure out how to solve it .

**Comment by dilas12345** [comment]
Hello please i am still facing the same issue with @NielEche  and @benjaminzanatta , tried all i could from changing the port, to changing from fetch to axios, and rewriting it again, still having same issue,
