### ISSUE TITLE
Flutter version???

### ISSUE THREAD

**Issue by marcellodesales** [cyrildiagne/ar-cutpaste#106]
Anyone has invested in porting this to Dart/Flutter?

**Comment by themysticsavages** [comment]
Why? I couldn't see a reason to.

**Comment by marcellodesales** [comment]
Multi-platform?

**Comment by themysticsavages** [comment]
Expo, the current app framework being used, can already export to multiple platforms.

**Comment by marcellodesales** [comment]
Well, I'm looking for a Data/Flutter version :) Just a preference... Thank you anyway...
