### ISSUE TITLE
main.py is not running

### ISSUE THREAD

**Issue by catchwayrk** [cyrildiagne/ar-cutpaste#15]
File "src/main.py", line 43
    logging.info(f"pong: {r.status_code} {r.content}" )
                                                    ^
SyntaxError: invalid syntax

**Comment by cyrildiagne** [comment]
Which version of python are you using? This code is only compatible with Python 3.6+

**Comment by catchwayrk** [comment]
(venv) RKMadugulas-MacBook-Pro:server yesbro$ python --version
Python 2.7.10
(venv) RKMadugulas-MacBook-Pro:server yesbro$ python3 --version
Python 3.8.2

**Comment by UchihaSR** [comment]
@catchwayrk your virtual environment is using the 2.7 version by default . create a symlink to python3. so that you can get the 3.8 version

**Comment by williamsiuhang** [comment]
Or create the virtual environment like this:
`virtualenv -p python3 venv`

which will use python3 in the virtual environment

**Comment by cyrildiagne** [comment]
Thanks @UchihaSR @williamsiuhang ! Added to the doc
