### ISSUE TITLE
Unable to resolve module '../../App' from 'node_modules/expo/AppEntry.js

### ISSUE THREAD

**Issue by justinedps26** [cyrildiagne/ar-cutpaste#21]
I got stuck on installing the app in my Expo app on my iOS device. 
I was able to access the app with the QR Code but once i was in Expo, I had the following error : 

```
Unable to resolve module '../../App' from 'node_modules/expo/AppEntry.js

None of these files exist:
*
App(.native|...........)
* App/index(.native|........)
```

I followed the steps you requested for the install. Can you help me out? I really want to test your project (but i am not familiar with this techno).

**Comment by sorianog** [comment]
Hello @justinedps26,

I am facing this issue as well. How did you resolve it on your end?
Thanks for any info!
