### ISSUE TITLE
Error Pasting & Image Not Copying

### ISSUE THREAD

**Issue by ondosansinaga** [cyrildiagne/ar-cutpaste#24]
When i start the the app
photo action not working and still not capture anything
and in Log, i see 

Cut
undefined
> taking image...
update
> resizing...
> sending to /cut...
> converting...
Done in 2.313s
Paste
> taking image...
update
> resizing...
> sending to /paste...
Done in 4.212s

when i place it in photoshop, nothing happen
I run with Latest python, windows 10 & android

![Screenshot_2020-05-06-15-07-14-80](https://user-images.githubusercontent.com/63991845/81156114-d3949400-8faf-11ea-94ec-9483052e314e.png)
![Screenshot_2020-05-06-15-36-37-71](https://user-images.githubusercontent.com/63991845/81156126-d55e5780-8faf-11ea-95f1-c421815c67a9.png)
![Screenshot_2020-05-06-15-36-42-90](https://user-images.githubusercontent.com/63991845/81156131-d68f8480-8faf-11ea-8b7b-4fee62d1a39b.png)
![Screenshot_2020-05-06-15-36-48-32](https://user-images.githubusercontent.com/63991845/81156134-d7281b00-8faf-11ea-95f1-acf952a33e0c.png)
![Screenshot_2020-05-06-15-36-52-32](https://user-images.githubusercontent.com/63991845/81156137-d7281b00-8faf-11ea-8781-f61f0e8ba2f8.png)

**Comment by cyrildiagne** [comment]
If you check in the local server folder, do you see the image files being added?

**Comment by ivoneijr** [comment]
Exactly the same here, 

Checking the server I have this created files: 

`
     cut_current.png
     cut_mask.png
     cut_received.jpg
     paste_received.jpg
`

**Comment by poohitan** [comment]
having exactly the same issue. hovewer sometimes pasting works without any errors, but just creates a blank layer in Photoshop.

**Comment by poohitan** [comment]
Finally managed to do a successfull paste. Looks like blank layers appear because screenpoint detects the point on the screen wrong. Works better when I capture the edge of the screen within the frame of the camera.

**Comment by jardicc** [comment]
Script will fail when there is no document.

Also try this snippet: https://github.com/cyrildiagne/ar-cutpaste/issues/2#issuecomment-623671398

I used `DialogModes.ERROR` so Photoshop will show error dialog if there is an error. When there would be `DialogModes.NO` then it throws an error but no dialog is shown so you need to be sure that errors are propagated correctly. Right now code is using PS DOM so you would need to set `app.playbackDisplayDialogs = DialogModes.ERROR` to achieve the same effect. Or wrap it into try/catch and show alert with error info on catch.

**Comment by ondosansinaga** [comment]
> 
> 
> Script will fail when there is no document.
> 
> Also try this snippet: [#2 (comment)](https://github.com/cyrildiagne/ar-cutpaste/issues/2#issuecomment-623671398)
> 
> I used `DialogModes.ERROR` so Photoshop will show error dialog if there is an error. When there would be `DialogModes.NO` then it throws an error but no dialog is shown so you need to be sure that errors are propagated correctly. Right now code is using PS DOM so you would need to set `app.playbackDisplayDialogs = DialogModes.ERROR` to achieve the same effect. Or wrap it into try/catch and show alert with error info on catch.

when i run  this code 
python src/main.py \
    --basnet_service_ip="http://X.X.X.X" \
    --basnet_service_host="basnet-http.default.example.com" \
    --photoshop_password 123456


this appear, how i can run this ?
![hm](https://user-images.githubusercontent.com/63991845/81284368-36f1f500-9088-11ea-9766-ce40eabbfd2a.PNG)

i also change the XXXX to local server
but it still error

**Comment by ondosansinaga** [comment]
> 
> 
> Script will fail when there is no document.
> 
> Also try this snippet: [#2 (comment)](https://github.com/cyrildiagne/ar-cutpaste/issues/2#issuecomment-623671398)
> 
> I used `DialogModes.ERROR` so Photoshop will show error dialog if there is an error. When there would be `DialogModes.NO` then it throws an error but no dialog is shown so you need to be sure that errors are propagated correctly. Right now code is using PS DOM so you would need to set `app.playbackDisplayDialogs = DialogModes.ERROR` to achieve the same effect. Or wrap it into try/catch and show alert with error info on catch.

i dont know how to make it happen, code above


but now i face new issues, that 
 "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'cut_mask.png'
![mask](https://user-images.githubusercontent.com/63991845/81295264-5b56cd00-909a-11ea-8d7a-dd05eb2cbc8e.PNG)

**Comment by cyrildiagne** [comment]
Can you please check if your BASNet service is working properly with cURL / Postman? There are a few other issues mentioning this issue and how to proceed.

**Comment by ondosansinaga** [comment]
> 
> 
> Can you please check if your BASNet service is working properly with cURL / Postman? There are a few other issues mentioning this issue and how to proceed.

Thank you guys!
i've already fix my connection

now i using
Android + Windows 10 + LocalHost 1 for server & app + LocalHost 2 for BASNET

i will close this ISSUE soon
thank you for helping

**Comment by ondosansinaga** [comment]
if you running in windows 10
just connect your localhost ip 1 (ex : 192.168.100.8:3000) to server.tsx and ake sure that ip and port
is exactly same to the IP in server/main.py (scroll down to the end)

for basnet-http i just create new localhost by using "netsh wlan start hostednetwork" and using this ip to basnet-http/main.py (scroll down to the end)

run the basnet-http
run the server
run the app

make sure when you run the server, BASNET_IP_SERVER is fill by basnet_http IP

hope you get help
sorry if make english bad
