### ISSUE TITLE
Is it possible to use this with older stand alone versions of Photoshop, like CS6?

### ISSUE THREAD

**Issue by rhst1** [cyrildiagne/ar-cutpaste#27]
Is it possible to use this with older stand alone versions of Photoshop, like CS6?

**Comment by ivoneijr** [comment]
@rhst1 Did you test it?

**Comment by rhst1** [comment]
No. Didn't see how I could since the server code requires a password for the remote connection to online Photoshop.

**Comment by ivoneijr** [comment]
I have no sure if it works for online photoshop.

The password required is to be used with photoshop remote access feature, see how to set up [here](https://medium.com/0xcc/how-to-turn-photoshop-into-a-remote-access-tool-805485a9480)

**Comment by rhst1** [comment]
Thank you!
