### ISSUE TITLE
Then update the IP address in components/Server.txt ->Server.tsx

### ISSUE THREAD

**Issue by sexyoung** [cyrildiagne/ar-cutpaste#34]
`Server.txt ->Server.tsx`

🐑

**Comment by cyrildiagne** [comment]
Fixed, Thanks!

**Comment by sexyoung** [comment]
@cyrildiagne by the way, I got some error message when cut.
first, I install the expo app at my iPhone
second, I run the server at my computer, like this:
```sh
python src/main.py --basnet_service_ip="http://172.16.50.149:8080" --photoshop_password 123456
```

then I open the mobile expo app, and focus something. but I see:
![image](https://user-images.githubusercontent.com/1787867/81399383-7b9b9000-915d-11ea-9c17-b582def67303.png)

orz

**Comment by cyrildiagne** [comment]
Can you check the results of the BASNet service when using cURL / Postman?

**Comment by sexyoung** [comment]
sorry, I dont know what is BASNet service... so I have no install any BASNet service.
but I have installed the server by https://github.com/cyrildiagne/ar-cutpaste/tree/master/server

If I miss something step, can give me some tip? thanks!
🐑

**Comment by cyrildiagne** [comment]
Please check step 2 in the main README. It provide links and some instructions on how to setup the BASNet service https://github.com/cyrildiagne/ar-cutpaste

**Comment by sexyoung** [comment]
@cyrildiagne  you mean this?
![image](https://user-images.githubusercontent.com/1787867/81472398-6e98a280-922a-11ea-945c-d765136ea866.png)

**Comment by sexyoung** [comment]
![image](https://user-images.githubusercontent.com/1787867/81473786-ac4df900-9233-11ea-96b0-79ba011e0ecf.png)

I test the image
![image](https://user-images.githubusercontent.com/1787867/81473802-c556aa00-9233-11ea-9935-87179b694a3d.png)

But I get a invalid image
![image](https://user-images.githubusercontent.com/1787867/81473829-eddea400-9233-11ea-9d29-8500591adc75.png)
