### ISSUE TITLE
Error 'atob' failed: The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by cladjidane** [cyrildiagne/ar-cutpaste#39]
I managed to make this prototype work (excellent by the way), but I regularly get errors on some objects: 'atob' failed: The string to be decoded is not correctly encoded. What's amazing is that the generated images (cut_*.jpg) are perfectly readable. Any idea what the problem is? Thanks!

**Comment by chakkale** [comment]
Yep same here, but it didnt even work for me, constantly giving this error.

**Comment by chakkale** [comment]
ok i think this is an error when it fails to generate a mask.

**Comment by chakkale** [comment]
Yeah, i have the same error constantly too, i can see the generated images locally but doesnt get pasted on photoshop or neither shows up on the app.

**Comment by cladjidane** [comment]
Nothing technical in that, but I've noticed that by taking the same object from different angles(zoom) I sometimes make mistakes, sometimes not.

**Comment by tangzhibao** [comment]
Yeah, i have the same problem too and it even dosen't work successfully once。before that, i do this:
![微信截图_20200511165301](https://user-images.githubusercontent.com/47908524/81542862-e5a77580-93a7-11ea-91ef-a486119812c8.png)
so that pasting can work, but i don't know how to resolve that:
![eefbc192d313a5eab69c84e6e0921bc](https://user-images.githubusercontent.com/47908524/81543348-87c75d80-93a8-11ea-91c6-8c86ee4aab7d.png)

**Comment by chakkale** [comment]
I tried the snipped edit you provided, now pasting kinda works, but i can see the pasted layer for a second on photoshop and it instantly disappears.

**Comment by LoryCool** [comment]
> I tried the snipped edit you provided, now pasting kinda works, but i can see the pasted layer for a second on photoshop and it instantly disappears.

Try to do CMD+Z (photoshop) and hopefully you will see the pasted image.

**Comment by buskerone** [comment]
> I tried the snipped edit you provided, now pasting kinda works, but i can see the pasted layer for a second on photoshop and it instantly disappears.

Try to do CMD+Z (photoshop) and hopefully you'll see image. Same thing happened to me.

**Comment by hitbittyboy** [comment]
I think it's a bug.

Sometimes image file's header is [data:image/png;base64,]....:
![image](https://user-images.githubusercontent.com/40710369/81998454-1aa41880-9685-11ea-8e37-85b3d9865102.png)

But the substring source is:
![image](https://user-images.githubusercontent.com/40710369/81998848-13c9d580-9686-11ea-98d4-9c83306e3249.png)


So modify the source like above, problem solves.
