### ISSUE TITLE
Cuba out of memory 

### ISSUE THREAD

**Issue by CalyphoZz** [cyrildiagne/ar-cutpaste#40]
Hello there,

first of all thanks for this amazing work, i worked so hard to install it because i'm not familiar to python ( still a good way to learn ! ). i believe the app is near to be fonctionnal.. but still have some error at the end.. i will put some screens if someone can help me out.

Basnet when i load it :
![basnet_ok](https://user-images.githubusercontent.com/12392555/81506462-c7357180-92f6-11ea-82d5-6b270814d1bc.JPG)

Server when i load it : 
![server_ok](https://user-images.githubusercontent.com/12392555/81506477-de745f00-92f6-11ea-9498-13c2df21d264.JPG)

app when i load it:
![app_ok](https://user-images.githubusercontent.com/12392555/81506492-f8ae3d00-92f6-11ea-8212-10b57a74a74c.JPG)

then i try to use the app , and an error occurs

the app seems to be ok : 
![app_ok_notOk](https://user-images.githubusercontent.com/12392555/81506509-1380b180-92f7-11ea-8797-71ca643111e1.JPG)

but...

basnet : 
![basnet_notok](https://user-images.githubusercontent.com/12392555/81506512-1e3b4680-92f7-11ea-8903-2567f6332dcb.JPG)

and server : 
![server_notok](https://user-images.githubusercontent.com/12392555/81506518-25625480-92f7-11ea-87ac-675e09dfc2af.JPG)

i dunno where i can change Cuba memory allowed or something like that.. if you guys have any ideas :), sorry for so many screens but i think it's more clear with it.

**Comment by Faqihyugos** [comment]
I have the same problem server error.
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'cut_mask.png'
![cannot identify image ](https://user-images.githubusercontent.com/32142762/81509432-d804d800-9334-11ea-8645-96e5c7f18a8d.jpeg)

**Comment by ondosansinaga** [comment]
make sure you run basnet-http and server in localhost or using docker, but i dont know how to use docker, i use localhost for both

when i run the app
first app will send to server and send to basnet and send back to server and send back to phone
i think like that

**Comment by ondosansinaga** [comment]
#24 

hope this will help you
scroll down

**Comment by CalyphoZz** [comment]
I didn't solve my problem with CUDA , so i uninstalled torch for cuda, and installed Torch without Cuda
