### ISSUE TITLE
Only cut working, doesnt paste anything

### ISSUE THREAD

**Issue by chakkale** [cyrildiagne/ar-cutpaste#41]
Hi. I managed to get this app working on my iPhone XS and Windows PC. It cuts the image and i can see the output png and jpg files on server. But it doesnt continue on paste command and i cant see it on my phone to paste on photoshop. it just gets stuck on cut and i have to restart the app for a new cut.  Also it throws an 'atob' error which i said on another issue post.

**Comment by ondosansinaga** [comment]
make sure you run basnet-http and server in localhost

**Comment by ondosansinaga** [comment]
#24 

hope this will help you
scroll down

**Comment by CalyphoZz** [comment]
> Hi. I managed to get this app working on my iPhone XS and Windows PC. It cuts the image and i can see the output png and jpg files on server. But it doesnt continue on paste command and i cant see it on my phone to paste on photoshop. it just gets stuck on cut and i have to restart the app for a new cut. Also it throws an 'atob' error which i said on another issue post.

Got exactly the same error, i have no error at all, it's cut, i can find : cut_received.png, cut_mask.png, cut_current.png in server file but nothing appear on my phone and i can't past anything

**Comment by jcytong** [comment]
@CalyphoZz 
I experienced the same thing and found out there's a timing issue.
You have to take a picture and **keep your finger** on the screen until you see the cropped image appear. Then point the camera at your computer and release to paste.

If you lift your finger before the server responds, the phone will try to paste an empty image.https://github.com/cyrildiagne/ar-cutpaste/blob/f556698d1566443b6fc78651440a415e63b63187/app/App.tsx#L146-L155
