### ISSUE TITLE
Public BASNet Predictor Availability

### ISSUE THREAD

**Issue by salanki** [cyrildiagne/ar-cutpaste#44]
Hello,

What you have built is super cool. I've set up a publicly available prediction endpoint for the BASNet model. This alleviates the need for people who want to play around with this to find/rent GPUs and run their own model instance. The model is running on an auto-scaling cluster of Tesla V100s, so inference performance should be great.

Simply run the server with `--basnet_service_ip http://basnet-predictor.tenant-compass.global.coreweave.com/` and you are good to go.

I intend to keep this online as long as there is interest, so you are welcome to publish it in getting started docs.

**Update**
A U-2-Net endpoint is also available, use  `--basnet_service_ip http://u2net-predictor.tenant-compass.global.coreweave.com/`. I believe the recommendation is to use this instead.

**Comment by DanielSalama1** [comment]
Thanks

**Comment by jcytong** [comment]
@salanki You're awesome!
You'll be awesomer if you can also do the same for U-2-Net? 😅
https://github.com/cyrildiagne/u2net-http

**Comment by jardicc** [comment]
Cool. Hopefully, I will be able to run it and improve PS scripts.

**Comment by cyrildiagne** [comment]
Wow @salanki that's pretty awesome (and quite generous)!
Would you be ok if I update the README to include that option?

**Comment by salanki** [comment]
@jcytong: U-2-Net is now up at: http://u2net-predictor.tenant-compass.global.coreweave.com.

@cyrildiagne: Yes, please add it to the README. If you can, a thank you to my employer (www.coreweave.com) would be nice in the README so I can keep sneaking away GPUs to support projects like these!

**Comment by jcytong** [comment]
Thanks @salanki 
You just became my favourite person in the world! Good thing my wife & mom are not on Github LOL....
