### ISSUE TITLE
Parse Empty Image to PS

### ISSUE THREAD

**Issue by pierrebrtr** [cyrildiagne/ar-cutpaste#5]
Hey ! Everything is working fine excepted one thing : the ps script is creating a new empty layer instead of parsing the image and the renaming is not working. Have someone got this issue ?

**Comment by cyrildiagne** [comment]
Hey!
Could you inspect the coordinates that are sent to `server/ps.py`?
Also I realise that I didn't explain in the README the issue with document offset (coordinates of the document from top left corner of the screen) and pixel density (retina vs non retina)
For now they must be manually edited in `server/ps.py`.

**Comment by pierrebrtr** [comment]
So, I have those document settings for photoshop as i tried to follow your script : 
![image](https://user-images.githubusercontent.com/11999669/80964492-40255c80-8e11-11ea-967b-8cd7a8ad9daa.png)

When i'm parsing i've got those coordinates : 1291 321

More precision : I'm running Windows 10 with last version of photoshop

**Comment by pierrebrtr** [comment]
Okay found out that this is the path for the image that is buggy with \. So just replace \ with / and it is working ! 
![image](https://user-images.githubusercontent.com/11999669/80976223-753aaa80-8e23-11ea-8259-4bcb7a329bc2.png) 
Just add this line in ps.py

**Comment by cyrildiagne** [comment]
Thanks a lot for getting to the bottom of this.
Very strange that photoshop requires unix like separators on Windows but this whole photoshop plugging part should be improved improved/rewritten so I've added your fix.

To answer your question about SCREEN_PIXELS_DENSITY, it's the density of your screen. On macbookpro, the retina display density is of 2 so screenshots are twice bigger. so it's not related to the resolution of the photoshop document!

Hope that helps.

**Comment by csgorham** [comment]
Hi!  I am having the same problem as pierre: working on a MacbookPro 2017 w/touchbar w/out retina.... my photoshop width/height dimensions are 2121 and 1280 ... i imagine that i just need to set the SCREEN_PIXELS_DENSITY correctly... any ideas?   Love this app!

**Comment by csgorham** [comment]
I guess i will set the X and Y offsets to zero...  i cannot figure out how to change them from 0 in photoshop.

**Comment by csgorham** [comment]
how does PPI (pixel per inch) convert the SCREEN_PIXEL_DESTITY

**Comment by csgorham** [comment]
https://engineering.fb.com/web/optimizing-for-the-macbook-pro-with-retina-display/

This helps i think.... i just want an image!!!! :)

**Comment by csgorham** [comment]
how does PPI (pixel per inch) convert the SCREEN_PIXEL_DESTITY

https://engineering.fb.com/web/optimizing-for-the-macbook-pro-with-retina-display/

This helps i think.... i just want an image!!!! :)  Im using SCREEN_PIXEL_DESTITY=1 and still not working for me

**Comment by csgorham** [comment]
it is a retina display actually.... now i am extra confused. Shoot... i will figure it out.

**Comment by csgorham** [comment]
It is loading the blank layer, so i figure everything is working well.  But is there any chance that i should have changed the basnet service ip to something besides HTTPConnectionPool(host='x.x.x.x', port=80) ?    ahh so close.
