### ISSUE TITLE
Can I add your app to React Native Apps ?

### ISSUE THREAD

**Issue by shoken0x** [cyrildiagne/ar-cutpaste#55]
It's cool! I think it would be helpful to other React Native developers. Can I add your app to React Native Apps showcase ?
https://github.com/ReactNativeNews/React-Native-Apps

**Comment by cyrildiagne** [comment]
Please fee free!

**Comment by shoken0x** [comment]
Hey @cyrildiagne , I pushed pull request and merged. 🎉
https://github.com/ReactNativeNews/React-Native-Apps/pull/132
