### ISSUE TITLE
got 500 when use "http://u2net-predictor.tenant-compass.global.coreweave.com"

### ISSUE THREAD

**Issue by huangWay** [cyrildiagne/ar-cutpaste#68]
I configured the "basnet_service_ip" with "http://u2net-predictor.tenant-compass.global.coreweave.com".
when sending to BASNet, the code "res = requests.post(args.basnet_service_ip, headers=headers, files=files )" in line 74 returns the code 500(internal error), can anybody help me?

**Comment by ChebroluTejaswi** [comment]
> I configured the "basnet_service_ip" with "http://u2net-predictor.tenant-compass.global.coreweave.com". when sending to BASNet, the code "res = requests.post(args.basnet_service_ip, headers=headers, files=files )" in line 74 returns the code 500(internal error), can anybody help me?

Even I am facing this issue?
How did you resolve it

**Comment by aiboom** [comment]
这是来自胡国良的自动回复邮件。
 
您好，谢谢您的来信，我已经收到您的信件，我会尽快给您回复。
