### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by RohanD007** [cyrildiagne/ar-cutpaste#77]
Can someone please explain how to install this from the start? I really need someone to explain the process.

**Comment by sorianog** [comment]
I am struggling with this as well. From the README, I followed the setup found here in the [/app](https://github.com/sorianog/ar-cutpaste/tree/master/app) folder. Attempted the `npm install` but got an error. Opened up the log file that was spat out in the terminal and it seems like there is a complaint with `package.json` ? 🤔   

It's my first time working with ReactNative. Were you able to get this sorted out? I forked the repo and will see what I can find out on my end.

**Comment by 5c13nc3Guy** [comment]
Unscribe me please

**Comment by sorianog** [comment]
TIL: You should run the commands in the correct directory....
I feel that this issue can be closed if others are able to run the app after seeing the comments here. 🤓
