### ISSUE TITLE
cannot identify image file 'cut_mask.png'

### ISSUE THREAD

**Issue by buskerone** [cyrildiagne/ar-cutpaste#8]
Hi, first of all thanks for this! It's really awesome. 

I'm having some issues when cutting out the image:

```
"cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'cut_mask.png'
```

Python 3.7

I can see three image files:

- paste_received.png (ok)
- cut_received.png (ok)
- cut_mask.png (not valid image)

Any ideas?

**Comment by tushardhadiwal** [comment]
@buskerone Are you able to see the cut image in the react app, as show in demo. I am not able to see it.

**Comment by buskerone** [comment]
I’m not able to see it because the png file is corrupted.

**Comment by tushardhadiwal** [comment]
@buskerone Do you think its the problem with Base64.tsx btoa function?

**Comment by buskerone** [comment]
I don't think the issue is in the client. I'm getting 405 Method not allowed when doing `request.post(ip, files=files)`.

**Comment by buskerone** [comment]
Ok, so I figured out what was the issue. I missed step 2! My bad. This is crucial.

**Comment by Charmve** [comment]
@buskerone could you please tell 'which step 2'?

**Comment by aiboom** [comment]
这是来自胡国良的自动回复邮件。
 
您好，谢谢您的来信，我已经收到您的信件，我会尽快给您回复。
