### ISSUE TITLE
TypeError: Network Request failed

### ISSUE THREAD

**Issue by anilxthakur** [cyrildiagne/ar-cutpaste#81]
After running code "npm install" and scan the QR code, I got Network failure.
**Both PC and mobile are on the same network.
**Windows PC
** Expo on Android 10
In my understanding, I found that its Reactive Native which causes the problem, but I don't know how to resolve it.
![Screenshot_2021-03-12-19-01-41-402_host exp exponent](https://user-images.githubusercontent.com/66789827/111022245-9da61480-83f7-11eb-9f4b-093b215c8bc6.jpg)
![Screenshot_2021-03-12-18-32-01-391_host exp exponent](https://user-images.githubusercontent.com/66789827/111022246-9f6fd800-83f7-11eb-835d-7740f7e9301b.jpg)
![Screenshot_2021-03-12-19-02-14-434_host exp exponent](https://user-images.githubusercontent.com/66789827/111022248-a0a10500-83f7-11eb-88a3-e42569d2198c.jpg)

**Comment by bansalaarav** [comment]
Go to the Server.tsx file in the app/components folder and change the URL on the 3rd line to the address you started the server on. For me it was "http://192.168.1.2:8080".

**Comment by anilxthakur** [comment]
I have already done it, but the same problem.

**Comment by anilxthakur** [comment]
> Go to the Server.tsx file in the app/components folder and change the URL on the 3rd line to the address you started the server on. For me it was "http://192.168.1.2:8080".

Hey you are using PC IP address or Photoshop server IP address?

**Comment by bansalaarav** [comment]
PC IP address. i.e. the address used in the flask server

**Comment by bansalaarav** [comment]
Also make sure that your server and app are running on the same wifi network.

**Comment by anilxthakur** [comment]
Thank you. It's solved.
