### ISSUE TITLE
[README|URL ISSUE] Easy to use app link broken.

### ISSUE THREAD

**Issue by prameshbajra** [cyrildiagne/ar-cutpaste#97]
The site `https://arcopypaste.app` is not accessible. Can you please update it?

![image](https://user-images.githubusercontent.com/16387512/131223862-e5a72e03-6069-41a0-88df-87c53cce4c3b.png)

Thank you.

**Comment by J-Filip** [comment]
same

**Comment by Aiyush-G** [comment]
Same

**Comment by clamquarter** [comment]
![image](https://user-images.githubusercontent.com/60370426/131257761-77b2dccb-1a78-46d4-8228-6dd1a2fe0b57.png)

**Comment by stefan-reich** [comment]
Yup.

Is the app in the app store? Not finding it there.

**Comment by Daniel-Mendes** [comment]
https://clipdrop.co/

**Comment by cyrildiagne** [comment]
Oops thanks a lot for spotting this. Link fixed: https://github.com/cyrildiagne/ar-cutpaste/commit/ce87d1b40c9b8345b610b5c97e4cdcdbf56d18d5
